Migrated from nose to pytest
evonove/django-money-rates pull request #21
Opened 2017-02-12 19:51 UTC by Alien1993

Test matrix had to be modified since Django master is not supporting Python 2 anymore and targeting only Django 2.0.

2017-03-21 10:59 UTC, Girbons requested changes

2017-03-21 10:59 UTC, Girbons commented on tests/test_commands.py
> +    with pytest.raises(CommandError):
assert the error message
```python
    with pytest.raises(CommandError) as exc:
        ....
     assert 'Message Exception' in str(exc.value)
```

2017-03-21 14:18 UTC, synasius commented on tests/test_commands.py
> +    with pytest.raises(CommandError):
agree

2017-06-07 12:45 UTC, Girbons approved these changes

2017-06-27 12:58 UTC, merged